

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
    
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author Mohamed owais
 */
public class loyatycard extends javax.swing.JFrame {

    /**
     * Creates new form loyatycard
     */
    public loyatycard() {
        initComponents();
    }

    static final String dburl = "jdbc:derby://localhost:1527/fatty";
    static final String dbdriver = "org.apache.derby.jdbc.ClientDriver";
    static final String dbusername = "fatty";
    static final String dbpassword = "admin";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(219, 97, 154, 38);

        jLabel1.setText("Loyalty Card Verification");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 50, 134, 33);

        jLabel2.setText("Enter Loyalty Card Number:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 97, 156, 38);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(147, 169, 85, 41);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        String CardNumber = jTextField3.getText();
        System.out.println("Button Clicked!!");
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;     
                try
                {
                    Class.forName(dbdriver);
                    connection  = DriverManager.getConnection(dburl, dbusername, dbpassword);
                    
                    statement=connection.createStatement();
                    resultSet = statement.executeQuery("select POINTS from FATTY.LOYALITY where number = '"+CardNumber+"'");
                    while(resultSet.next())
                    {
                        System.out.println("Inside ResultSet WhileLoop-OO");
                        Points next = new Points(Long.parseLong(CardNumber));
                        next.setVisible(true);
                        setVisible(false);                      
                       
                    }
                }
                catch(SQLException | ClassNotFoundException ex)
                {
                    System.out.println(ex);
                }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loyatycard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loyatycard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loyatycard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loyatycard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loyatycard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
