/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Mohamed owais
 */
public class Memberportal extends javax.swing.JFrame {

    /**
     * Creates new form Memberportal
     */
    public Memberportal() {
        initComponents();
    }
    static final String dburl = "jdbc:derby://localhost:1527/fatty";
    static final String dbdriver = "org.apache.derby.jdbc.ClientDriver";
    static final String dbusername = "fatty";
    static final String dbpassword = "admin";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 70, 70, 20);

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 120, 70, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 70, 180, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(200, 110, 180, 30);

        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 170, 100, 40);

        jLabel4.setText("Member Portal (Login)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 30, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Button Clicked!!");
        String username = jTextField1.getText();
        String password = jPasswordField1.getText();
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;     
                try
                {
                    Class.forName(dbdriver);
                    connection  = DriverManager.getConnection(dburl, dbusername, dbpassword);
                    
                    statement=connection.createStatement();
                    resultSet = statement.executeQuery("select * from FATTY.LOGIN where username = '"+username+"'");
                    while(resultSet.next())
                    {
                        System.out.println("Inside ResultSet WhileLoop-OO");
                        if(password.equals(resultSet.getString(2)))
                        {
                            
                            loyatycard next = new loyatycard();
                            next.setVisible(true);
                            this.setVisible(false);
                        }
                        
                        else 
                        {
                            successmsg next = new successmsg();
                            next.setVisible(true);
                        }
                    }
                }
                catch(SQLException | ClassNotFoundException ex)
                {
                    System.out.println(ex);
                }
//                finally
//                {
//                    try 
//                    {
//                        resultSet.close();
//                        statement.close();
//                        connection.close();
//                    } 
//                    catch (SQLException ex) 
//                    {
//                        Logger.getLogger(Memberportal.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                            
//                          
//                }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Memberportal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Memberportal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Memberportal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Memberportal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Memberportal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
